#!/bin/sh

wall=$(find ~/pix/wall/ -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)

# set the wallpaper
xwallpaper --zoom $wall

# generate the color scheme for the wallpaper
wal -c
wal -i $wall

# generate the color scheme for the status bar
xdotool key super+F5
