#!/bin/sh

wall=$(find ~/Pictures/Wallpapers/ -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)

# set the wallpaper
feh --bg-fill $wall

# generate the color scheme for the wallpaper
wal -c
wal -i $wall

# generate the color scheme for the status bar
xdotool key super+F5
